# Generated by Django 5.0.7 on 2024-10-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='created_at',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='construction_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
