# Generated by Django 5.0.7 on 2024-10-24 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_imageupload_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageupload',
            name='prices_materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
