# Generated by Django 5.0.7 on 2024-11-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermood',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='usermood',
            name='user',
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
        migrations.DeleteModel(
            name='UserMood',
        ),
    ]
